export ZSH=$HOME/.oh-my-zsh
export EDITOR=nvim
export VISUAL=nvim

plugins=(git common-aliases zsh-autosuggestions)
ZSH_THEME="lambda"

source $ZSH/oh-my-zsh.sh
# zle_highlight=(default:bold)

ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=60'
TERM=xterm-256color
