name: Build Multi-Arch Docker Images

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: swoole-workspace

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment:
          - name: Base
            context: ./Base
            dockerfile: Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          - name: Web
            context: ./Web
            dockerfile: Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          - name: Worker
            context: ./Worker
            dockerfile: Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          - name: CI
            context: ./CI
            dockerfile: Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          - name: Dev
            context: ./Dev
            dockerfile: Dockerfile
            image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag
        id: extract_tag
        run: echo "::set-output name=tag::$(echo ${{ github.ref }} | awk -F '/' '{print $NF}')"

      - name: Convert tag to lowercase
        id: convert_to_lowercase
        run: echo "::set-output name=env_lowercase::${{ matrix.environment.name | awk '{print tolower($0)}' }}"

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.environment.context }}
          dockerfile: ${{ matrix.environment.dockerfile }}
          push: true
          tags: |
            ${{ matrix.environment.image }}:${{ steps.extract_tag.outputs.tag }}-${{ steps.convert_to_lowercase.outputs.env_lowercase }}
          environments: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Clean Docker cache
        run: |
          docker builder prune --all --force
