name: Build Multi-Arch Docker Images

on:
  push:
    tags:
      - "*"

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/swoole-workspace

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment:
          - name: Base
            context: ./Base
          - name: Web
            context: ./Web
          - name: Worker
            context: ./Worker
          - name: CI
            context: ./CI
          - name: Dev
            context: ./Dev
      fail-fast: true
      max-parallel: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag
        id: extract_tag
        run: echo "::set-output name=tag::$(echo ${{ github.ref }} | awk -F '/' '{print $NF}')"

      - name: Convert tag to lowercase
        id: convert_to_lowercase
        run: echo "::set-output name=env_lowercase::$(echo ${{ matrix.environment.name }} | awk '{print tolower($0)}')"

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.environment.context }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.extract_tag.outputs.tag }}-${{ steps.convert_to_lowercase.outputs.env_lowercase }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Clean Docker cache
        run: |
          docker builder prune --all --force
